import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
	index("routes/home.tsx"),
	route("login", "routes/login.tsx"),
	route("emotion", "routes/emotion.tsx"),
	route("chat", "routes/chat.tsx"),
	route("community", "routes/community.tsx"),
	route("community/write", "routes/community.write.tsx"),
	route("community/:postId", "routes/community.$postId.tsx"),
	route("dashboard", "routes/dashboard.tsx"),
	route("metrics", "routes/metrics.tsx"),
	route("profile", "routes/profile.tsx"),
	route("challenge", "routes/challenge.tsx"),
	route("help", "routes/help.tsx"),
	route("admin", "routes/admin.tsx"),
	route("error", "routes/error.tsx"),
	route("avatar-demo", "routes/avatar-demo.tsx"),
	route("home-improve", "routes/home_improve.tsx"),
	route("login-improve", "routes/login_improve.tsx"),
	route("dashboard-improve", "routes/dashboard_improve.tsx"),
	route("emotion-improve", "routes/emotion_improve.tsx"),
	route("chat-improve", "routes/chat_improve.tsx"),
	route("community-improve", "routes/community_improve.tsx"),
	route("challenge-improve", "routes/challenge_improve.tsx"),
	route("profile-improve", "routes/profile_improve.tsx"),
] satisfies RouteConfig;
